version: '3'
services:
  mongodb:
    image: 'bitnami/mongodb:4.2'
    ports:
      - "27018:27017"
    environment:
      - MONGODB_USERNAME=mongoadmin
      - MONGODB_PASSWORD=secret
      - MONGODB_DATABASE=mongobee